### PR TITLE
feat & test: support rich text

### PR DESCRIPTION
**Pull request by dankang**
* support rich text string
* add rich text test case
* ~disable saxTrim for keep blank in string~
* add saxTrim option for keep blank in string or not

### CODE REVIEW

**Comment by DaSpawn** [comment]
- the saxTrim option may be a signification change in functionality (I hated turning on,all I remember was a problem in the beginning and unsure what the problem was now).  could add it as an option though
- lib/worksheet.js changes were just pulled in with #27, not sure if it would conflict/be issue (they are exactly the same)

**Comment by dankang** [comment]
@DaSpawn I added the `saxTrim` option.

**Comment by dankang** [comment]
Can you publish lastest master branch to npm if you don't mind?

**Comment by dankang** [comment]
Ah, actually I fixed it and I am checking other things.
You don't have to rollback. I will fix below
```
// original code
  if (nodeObjName && nodeObjName.name === 't') {
    self.workBookSharedStrings.push(nodeObjValue)
  } else {
    if (nodeObjValue && typeof nodeObjValue === 'object' && nodeObjValue.hasOwnProperty('name') && nodeObjValue.name === 't') {
      self.workBookSharedStrings.push('')
    }
  }

// I fixed yesterday
  var isSharedStringItem = !!nodeData.find((n) => n && n.name === 'si') // <si> tag
  if (isSharedStringItem) {
    if (nodeObjName && nodeObjName.name === 't') {
      self.workBookSharedStrings.push(nodeObjValue)
    } else {
      self.workBookSharedStrings.push('')
    }
  } else {
    if (nodeObjName && nodeObjName.name === 't') {
      self.workBookSharedStrings[self.workBookSharedStrings.length - 1] += nodeObjValue
    }
  }

// new code
  var isSharedStringItem = !!nodeData.find((n) => n && n.name === 'si') // <si> tag
  if (isSharedStringItem) {
    if (nodeObjName && nodeObjName.name === 't') {
      self.workBookSharedStrings.push(nodeObjValue)
    } else {
      self.workBookSharedStrings.push('')
    }
  } else {
    if (nodeObjName && nodeObjName.name === 't') {
      self.workBookSharedStrings[self.workBookSharedStrings.length - 1] += nodeObjValue
    } else if (nodeObjValue && typeof nodeObjValue === 'object' && nodeObjValue.hasOwnProperty('name') && nodeObjValue.name === 't') {
      self.workBookSharedStrings.push('')
    }
  }
```

**Comment by dankang** [comment]
@kikill95 
If there is a rich-text cell, the xml is like below:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<sst xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" count="1" uniqueCount="1">
  
  <si><r><rPr><sz val="10"/><rFont val="Arial"/><family val="2"/></rPr><t xml:space="preserve">This is </t></r>
    <r><rPr><b val="true"/><sz val="10"/><color rgb="FFFF3333"/><rFont val="Arial"/><family val="2"/></rPr><t xml:space="preserve">only one</t></r>
    <r><rPr><sz val="10"/><rFont val="Arial"/><family val="2"/></rPr><t xml:space="preserve"> sentence.</t></r></si>
</sst>
```
1. nodeObjName.name='t', value='This is '
2. nodeObjName.name='t', value='only one'
3. nodeObjName.name='t', value='sentence.'

Because the original code recognizes three text, there is some problem.
So, I fixed. I will PR Soon. sorry.

**Comment by dankang** [comment]
@kikill95 Please rollback the code, I want to inspect it more.
I will PR later. Sorry!

**Comment by kikill95** [comment]
@dankang @DaSpawn I did a rollback
@dankang thank you for contributing, good luck and let us know if any help is needed =)

**Comment by dankang** [comment]
@kikill95 @DaSpawn Thank you for this great project.
I usually handle 500k+ rows xlsx files.
This is great.

**Comment by DaSpawn** [comment]
revert all set.  great to hear it works well, thanks!

**Pull request merged**
