### PR TITLE
feat & test: support rich text

### PR DESCRIPTION
**Pull request by dankang**
Last PR
* support rich text string
* add rich text test case
* add saxTrim option for keep blank in string or not

Added
* I fixed https://github.com/DaSpawn/xlsx-stream-reader/pull/28
* I moved the code finding '\<si\>'
```js
var isSharedStringItem = !!nodeData.find((n) => n && n.name === 'si') // <si> tag
```
* I think it works well.

### CODE REVIEW

**Comment by dankang** [comment]
@DaSpawn I had forgotten about this issue. I fixed the `test case conflict`.
Can you check this again and merge if it is OK?

**Comment by DaSpawn** [comment]
please let me know if need to update npm/version for this

**Comment by dankang** [comment]
If you update npm version, it will be very helpful for me. Thanks!

**Comment by DaSpawn** [comment]
updated earlier today

**Pull request merged**
